import https from "node:https";
import fs from "node:fs";
import path from "node:path";
import type { Server, IncomingMessage, ServerResponse } from "node:http";
import { faker } from "@faker-js/faker";
import { demoRawPullsForRepo, DEMO_USERNAME } from "../../src/background/demoData";
import type { PullRequest } from "../../src/background/fetchPullRequests";

// 1x1 solid green PNG — stands in for the pravatar.cc avatar photos that
// demo data points at (mapped to this server via --host-resolver-rules)
const AVATAR_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "base64"
);

/**
 * Local HTTPS stand-in for api.github.com (and i.pravatar.cc). The E2E
 * browser maps both hosts to this server via --host-resolver-rules, so no
 * real GitHub/avatar traffic happens and no credentials are needed.
 *
 * Behavior:
 * - GET /user            → the DEMO-mode username (see demoData.ts)
 * - GET /repos/<repo>/pulls → PRs generated by the DEMO-mode generator
 *   (demoRawPullsForRepo), re-seeded per response so each fetch returns
 *   different-but-deterministic data — tests tell fetches apart by content
 * - repos whose path contains "sso" get a 403 with an X-GitHub-SSO header
 *   to exercise the SSO-authorization error path
 * - anything else (pravatar avatar URLs) → a tiny PNG
 */
export class GitHubStubServer {
  port = 0;
  /** Artificial delay for /repos/... responses, to expose cache-first rendering. */
  delayMs = 0;
  /** Every /repos/... response, in order (for asserting fetch counts). */
  repoFetches: string[] = [];

  private server?: Server;
  private batch = 0;

  async start(): Promise<void> {
    const cert = fs.readFileSync(path.join(__dirname, "cert.pem"));
    const key = fs.readFileSync(path.join(__dirname, "key.pem"));
    this.server = https.createServer({ cert, key }, (req, res) => this.handle(req, res));
    await new Promise<void>((resolve) => {
      this.server!.listen(0, "127.0.0.1", resolve);
    });
    this.port = (this.server!.address() as { port: number }).port;
  }

  async stop(): Promise<void> {
    await new Promise<void>((resolve, reject) => {
      this.server?.close((err) => (err ? reject(err) : resolve()));
    });
  }

  private handle(req: IncomingMessage, res: ServerResponse): void {
    const sendJson = (status: number, body: unknown, headers: Record<string, string> = {}) => {
      res.statusCode = status;
      res.setHeader("content-type", "application/json");
      for (const [name, value] of Object.entries(headers)) res.setHeader(name, value);
      res.end(JSON.stringify(body));
    };

    if (req.url === "/user") {
      sendJson(200, { login: DEMO_USERNAME });
      return;
    }

    const pulls = req.url?.match(/^\/repos\/([^/]+\/[^/]+)\/pulls/);
    if (pulls) {
      const repo = pulls[1];
      this.repoFetches.push(repo);

      if (repo.includes("sso")) {
        sendJson(
          403,
          { message: "Resource protected by organization SSO enforcement" },
          { "X-GitHub-SSO": "required; url=https://github.com/orgs/acme/sso?token=abc123" }
        );
        return;
      }

      // Same generator as DEMO mode, re-seeded per response: every fetch
      // returns a fresh, deterministic batch of demo PRs
      faker.seed(this.batch++);
      const body: PullRequest[] = demoRawPullsForRepo(repo, DEMO_USERNAME);
      setTimeout(() => sendJson(200, body), this.delayMs);
      return;
    }

    // Avatar URLs (i.pravatar.cc/...) and anything else
    res.setHeader("content-type", "image/png");
    res.end(AVATAR_PNG);
  }
}
